### ISSUE TITLE
客户端使用什么播放器？

### ISSUE THREAD

**Issue by MalavitaC** [AirDwing/wqcloud-video#2]
生成的视频直播地址，要用什么播放器播放？小程序中可以使用吗？

**Comment by willin** [comment]
ref: https://cloud.tencent.com/document/product/266/14774

wxapp ref: https://www.w3cschool.cn/weixinapp/weixinapp-video.html

**Comment by MalavitaC** [comment]
之前没有表达清楚。是这样的，就在前两天，我正在着手一个视频点播的小程序，原本的思路是：后台将视频资源上传腾讯云视频点播服务，小程序上使用视频资源地址直接播放视频。可是后来发现点播服务的视频只有安卓、IOS和WEB播放器，小程序中无法使用。今天看到这个插件一下兴奋了，但是我在文档里没有看到点播相关资料，所以来问下。

**Comment by willin** [comment]
本插件跟客户端播放器无关。你还可以参考官方文档视频组件模块： https://developers.weixin.qq.com/miniprogram/dev/component/video.html
